# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - YoungTech

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  SERVER_NAME: ${{ secrets.SERVER_NAME }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  USER: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.SERVER_NAME }}
  PORT: ${{ secrets.PORT }}
  PROD: ${{ secrets.SERVER_NAME }}
  BLOB_CONNECTION: ${{ secrets.BLOB_CONNECTION }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      - name: Install backend dependencies
        run: |
          cd server
          npm install
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            frontend/dist
            server/*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8C018CEED9984645BC3B0A66DCF5D25E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F1F72A792B9948F1A4636B591CE1AE5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_914828291CF24F4CA0BC44E807386EC1 }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "YoungTech"
          slot-name: "Production"
          package: .

      # Custom startup command to run 'cd server && npm start'
      - name: Set custom startup command for Azure
        run: |
          az webapp config set --resource-group "test" --name "youngTech" --startup-file "npm run start"
